on:
  workflow_call:
    secrets:
      GITLEAKS_LICENSE_KEY:
        required: true

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure GitLeaks
        if:  hashFiles('.gitleaks.toml') == ''
        run: |
          curl -O https://raw.githubusercontent.com/smallstep/workflows/master/.gitleaks.toml
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE_KEY }}
          GITLEAKS_ENABLE_COMMENTS: true
      - uses: github/codeql-action/upload-sarif@v2
        if: always() && hashFiles('results.sarif') != ''
        with:
          sarif_file: results.sarif

