on:
  workflow_call:

jobs:
  lint:
    uses: smallstep/workflows/.github/workflows/goLint.yml@main

  test:
    uses: smallstep/workflows/.github/workflows/goTest.yml@main

  build:
    uses: smallstep/workflows/.github/workflows/goBuild.yml@main
