on:
  workflow_call:
    inputs:
      os-dependencies:
        required: false
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: false
      PAT:
        required: false
      CODECOV_TOKEN:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.19']
    steps:
      - name: Install Dependencies
        if: ${{ inputs.os-dependencies != '' }}
        run: |
          sudo apt-get install ${{ inputs.os-dependencies }}
      - name: Setup SSH key for private dependencies
        uses: webfactory/ssh-agent@v0.5.3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        if: ${{ env.SSH_PRIVATE_KEY != '' }}
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Checkout w/ PAT
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT != '' }}
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: true
      - name: Checkout w/out PAT
        env:
          PAT: ${{ secrets.PAT }}
        if: ${{ env.PAT == '' }}
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          check-latest: true
      - name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@v1.8.1
      - name: Run Test Suite
        run: |
          gotestsum -- -coverprofile=coverage.out -covermode=atomic ./...
        env:
          GOTESTSUM_JSONFILE: gotestsum.json
      - name: Annotate Test Suite Results
        if: ${{ (success() || failure()) && hashFiles('gotestsum.json') != '' }}
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: gotestsum.json
      - name: Codecov
        uses: codecov/codecov-action@v1.2.1
        if: matrix.go == '1.19'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
