on:
  workflow_call:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.19']
    steps:
      -
        name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      -
        name: Install gotestsum
        run: |
          go install gotest.tools/gotestsum@v1.8.1
      -
        name: Checkout Code
        uses: actions/checkout@v3
      -
        name: Run Test Suite
        run: |
          gotestsum -- -race -coverpkg=./... -coverprofile=coverage.out -covermode=atomic ./...
        env:
          GOTESTSUM_JSONFILE: gotestsum.json
      -
        name: Annotate Test Suite Results
        if: ${{ (success() || failure()) && hashFiles('gotestsum.json') != '' }}
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: gotestsum.json
      -
        name: Codecov
        uses: codecov/codecov-action@v1.2.1
        if: matrix.go == '1.19'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)

