on:
  workflow_call:

jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - name: Install libpcsclite-dev # Some dependencies require this package
        run: sudo apt-get install libpcsclite-dev
      - name: Run govulncheck
        run: govulncheck ./...
